#!/usr/bin/env bash
# Regenerates scripts/game_version.gd with the current git short commit hash.
#
# This is a MANUAL pre-export step, not automatic. Run it right before every
# Godot export (same pattern this project already follows for "rebuild after
# code changes" on other export targets). If you export without running this
# first, the exported build keeps whatever VERSION was baked in the last time
# this script ran (or "dev" if it has never been run), which will make the
# online version check reject joins against builds that actually differ.
#
# Usage (from anywhere):
#   scripts/tools/generate_version.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

if ! git rev-parse --short HEAD >/dev/null 2>&1; then
  echo "generate_version.sh: not a git repo (or no commits yet) — aborting, game_version.gd left untouched." >&2
  exit 1
fi

HASH="$(git rev-parse --short HEAD)"
if ! git diff --quiet --ignore-submodules -- . ':!scripts/game_version.gd' 2>/dev/null || \
   ! git diff --cached --quiet --ignore-submodules -- . ':!scripts/game_version.gd' 2>/dev/null; then
  HASH="${HASH}-dirty"
fi

OUT_FILE="$REPO_ROOT/scripts/game_version.gd"

cat > "$OUT_FILE" <<EOF
extends Node
## Autoloaded as "GameVersion". GENERATED FILE — do not hand-edit.
## Regenerated by scripts/tools/generate_version.sh, which must be run manually
## before every export. Holds the git short commit hash (plus "-dirty" if the
## working tree had uncommitted changes when generated) baked in at generation
## time. NetworkManager sends this string when creating/joining an online room
## so mismatched client builds can be rejected before they start a match.

const VERSION := "$HASH"
EOF

echo "Wrote $OUT_FILE with VERSION = \"$HASH\""
