extends Node
## Autoloaded as "GameVersion". GENERATED FILE — do not hand-edit.
## Regenerated by scripts/tools/generate_version.sh, which must be run manually
## before every export. Holds the git short commit hash (plus "-dirty" if the
## working tree had uncommitted changes when generated) baked in at generation
## time. NetworkManager sends this string when creating/joining an online room
## so mismatched client builds can be rejected before they start a match.

const VERSION := "8774e1d"
